puts "donners moi un nombre entre 1 et 25"
pyramide = gets.chomp.to_i
if 
    pyramide == 1
    print "#"
elsif
    pyramide == 2
    puts "#"
    puts "##"
elsif
    pyramide == 3
    puts "#"
    puts "##"
    puts "###"
elsif
    pyramide == 4
    puts "#"
    puts "##"
    puts "###"
    puts "####"
elsif
    pyramide == 5
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
elsif
    pyramide == 6
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
elsif
    pyramide == 7
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
elsif
    pyramide == 8
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"

elsif
    pyramide == 9
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
elsif
    pyramide == 10
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
elsif
    pyramide == 11
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
elsif
    pyramide == 12
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
elsif
    pyramide == 13
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
elsif
    pyramide == 14
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
elsif
    pyramide == 15
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    

elsif
    pyramide == 16
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
elsif
    pyramide == 17
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
elsif
    pyramide == 18
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
elsif
    pyramide == 19
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
elsif
    pyramide == 20
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
elsif
    pyramide == 21
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
    puts "######################"
elsif
    pyramide == 22
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
    puts "######################"
    puts "#######################"
elsif
    pyramide == 22
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
    puts "######################"
    puts "#######################"
elsif
    pyramide == 24
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
    puts "######################"
    puts "#######################"
    puts "########################"
elsif
    pyramide == 25
    puts "#"
    puts "##"
    puts "###"
    puts "####"
    puts "#####"
    puts "######"
    puts "#######"
    puts "########"
    puts "#########"
    puts "##########"
    puts "###########"
    puts "############"
    puts "#############"
    puts "##############"
    puts "###############"
    puts "################"
    puts "#################"
    puts "##################"
    puts "####################"
    puts "#####################"
    puts "######################"
    puts "#######################"
    puts "########################"
    puts "#########################"
end
